micronaut:
  application:
    name: ec-szperacz
  server:
    cors:
      enabled: true

redis:
  uri: redis://localhost:6379

logger:
  levels:
    io.lettuce.core: ERROR

szperacz:
  event-fetch-limit: 25000
  test-producer-directory: "C:\\Users\\kkwit\\IdeaProjects\\il\\szperacz\\test\\data"
  kafka:
    group-id: szperacz
    bootstrap-servers: localhost:9092
  catalog:
    path: '/szperacz_catalog/'
    compress-files: false
